# Use an official Node.js runtime as base image
FROM node:20-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first (for better caching)
COPY package*.json ./


# Copy rest of the app code
COPY . .

# Install dependencies
RUN npm install

# Expose port (match the port in your app)
EXPOSE 3000

# Command to run the app
CMD ["node", "src/index.js"]
